// figures
export const ADD_NEW_FIGURE = 'ADD_NEW_FIGURE'
export const INC_MAX_ID = 'INC_MAX_ID'
export const Z_INDEX_UPDATE = 'Z_INDEX_UPDATE'
export const GET_ACTIVE_FIGURE = 'GET_ACTIVE_FIGURE'
export const RESET_ACTIVE_FIGURE = 'RESET_ACTIVE_FIGURE'
export const SAVE_POSITION = 'SAVE_POSITION'
export const GET_NEW_COLOR_TO_ACTIVE_FIGURE = 'GET_NEW_COLOR_TO_ACTIVE_FIGURE'
export const DELETE_KEY_LISTENER = 'DELETE_KEY_LISTENER'

// fill
export const SET_DEFAULT_FILL_COLOR = 'SET_DEFAULT_FILL_COLOR'
export const SET_FILL_COLOR = 'SET_FILL_COLOR'